CREATE TABLE IF NOT EXISTS tasks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    owner_id text NOT NULL,
    description text NULL CHECK (
        description IS NULL
        OR (char_length(description) > 10 AND char_length(description) < 50)
    ),
    priority text NULL CHECK (
        priority IS NULL
        OR priority IN ('High', 'Medium', 'Low')
    ),
    status text NULL CHECK (
        status IS NULL
        OR status IN ('Pending', 'InProgress', 'Completed', 'Cancelled')
    ),
    created timestamp with time zone NOT NULL,
    created_by text NOT NULL,
    last_modified timestamp with time zone NOT NULL DEFAULT now(),
    last_modified_by text NULL
);
